name: Deploy Swagger File to S3 Bucket

on:
  push:
    paths:
      - swagger/swagger.json

jobs:

  uploadSwagger:
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3

      - id: s3Swagger
        name: Upload Swagger to S3
        run: aws s3 cp ./swagger/swagger.json s3://${{ secrets.swagger_bucket_name }}/iris-service-api/swagger/
